### ISSUE TITLE
Does not work with latest Dioxus version (0.3.1)

### ISSUE THREAD

**Issue by BartBM** [nissy-dev/dioxus-free-icons#19]
The crate worked with Dioxus 0.2.4 but since upgrading to 0.3.1, this compile error occurs whenever using an Icon:
```
79  | |                 Icon {
    | |                 ^^^^ expected `&Scoped<'_, _>`, found struct `dioxus_core::scopes::Scope`
```

**Comment by nissy-dev** [comment]
Thanks! I released the new version for Dioxus version 0.3.1.
