### ISSUE TITLE
Breaking changes in Dioxus master branch

### ISSUE THREAD

**Issue by esimkowitz** [nissy-dev/dioxus-free-icons#23]
Heads-up there are breaking changes coming in the next release from Dioxus. I haven't fully evaluated what changed, but updating the Dioxus references to the latest git ref from master resolved the build errors. I have a forked branch that references this latest ref if others run into the same issue. When the next version is released, I'll update it to point to the stable version and open a PR.

https://github.com/esimkowitz/dioxus-free-icons

**Comment by nissy-dev** [comment]
Resolved by #20
